### PR TITLE
Added dynamic callbacks mode functionality

### PR DESCRIPTION
**Pull request by Alex-Sh**

### CODE REVIEW

**Comment by dercoder** [comment]
Hi, please use omnipay functions for this: returnUrl, cancelUrl, notifyUrl
https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractRequest.php#L554

**Comment by dercoder** [comment]
And please show me the docs. i could not found anything in ecoPayz_MIG_2.0.3.pdf. Maybe my one is deprecated

**Comment by Alex-Sh** [comment]
Hello

https://drive.google.com/file/d/0B_rU0L61HpZjS0dJZmcxdTlnT2s/view?usp=sharing

**Comment by dercoder** [comment]
OnSuccessUrl = returnUrl
OnFailureUrl = cancelUrl
TransferUrl = notifyUrl
If you want to add CancellationUrl and CallbackUrl please also add request handlers

**Comment by dercoder** [comment]
Please check my latest commit

**Comment by Alex-Sh** [comment]
Thanks. What do you mean on adding request handlers for Cancel and Callback URL? Like CompletePurchaseRequest.php? I think CallbackUrl shares the same request/response, not sure about CancellationUrl.

**Comment by dercoder** [comment]
Yes, like CompletePurchaseRequest.php. Please find out how CallbackUrl and CancellationUrl work and please test current master branch with "returnUrl", "cancelUrl" and "notifyUrl"

**Comment by Alex-Sh** [comment]
Current master works well.

This is EcoPayz response about Callback and Cancellation functionality:

> Crediting account after getting callback message is more secure because we finalise transaction on our end only after receiving your <SVSPurchaseStatusNotificationResponse>. If your confirmation response does not reach us, then we mark transaction as failed. However, your system will consider transaction to be successful as a result you might be crediting client with money that were not transferred to you.
> 
> Here is the sample of the successful callback:
> <?xml version="1.0" encoding="utf-8"?><TransactionResult xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ErrorCode>0</ErrorCode><Message>OK</Message><SvsTxID>1573010000033532608</SvsTxID><TransactionType>Purchase</TransactionType><ProcessingTime>20150406 11:06:56</ProcessingTime><Amount>100</Amount><Currency>EUR</Currency><MerchantAccountNumber>100000</MerchantAccountNumber><ClientAccountNumber>1112345975</ClientAccountNumber><TransactionDescription /><ClientTransactionID>1428318397A3E932B549</ClientTransactionID></TransactionResult>
> 
> The only positive callback is <ErrorCode>0</ErrorCode>. If you get any other code or dont get a callback at all, you must decline transaction on your end.
> 
> CancellationUrl. This is optional url and therefore optional function. Our system can reverse successful customer deposits with merchants. The reversal can be initiated only by us by sending <SVSPurchaseStatusNotificationRequest> with status 5 to the CancellationURL.
> This is optional feature because we can reverse deposits without sending a notification (but only after investigating each such case with the merchant and getting approval)

So we can receive CallbackUrl data just using  $gateway->completePurchase(); and there is no need to make a response. This is working fine. And CancellationURL is same as TransferUrl, so no need to create new handlers.

Can you please add an option to define Callback and Cancellation URLs?

**Comment by dercoder** [comment]
So CallbackUrl = TransferUrl = notifyUrl?
Is this correct?

**Comment by Alex-Sh** [comment]
Not really
TransferUrl - We will receive <SVSPurchaseStatusNotificationRequest> and we should send <SVSPurchaseStatusNotificationResponse>
NotifyUrl = TransferUrl in terms of Omnipay
CallbackUrl  - We will receive <TransactionResult> and no need to response, and it still can be processed with completePurchase(), like TransferUrl

**Comment by dercoder** [comment]
so CallbackUrl is like TransferUrl but dont need any response? so why we cant use Omnipay NotifyUrl for Callback and Transfer?

**Comment by dercoder** [comment]
CompletePurchaseRequest will only return a response on the second request for confirmation. The data is the same. My conclusion TransferUrl = CallbackUrl.

TransferUrl:
Merchant’s **Listener URL** (used for server to server calls between the Merchant and ecoPayz)

CallbackUrl:
It can be the **same URL as your Listener** or a different URL

**Comment by Alex-Sh** [comment]
I think we need to keep them different, because there can be different processing logic - logging, applying transaction (only on Callback), etc. 
For example I will make Merchant side processing only on CallbackUrl, like it should be, and TransferUrl will be only used to accept/decline transactions according to EcoPayz request.

**Comment by dercoder** [comment]
Please ask the omnipay community how we should handle this: https://github.com/thephpleague/omnipay

**Comment by Alex-Sh** [comment]
Quick example, just to clarify what I want to achieve

Callbacks: http://prntscr.com/btp6iz
PurchaseRequest class: http://prntscr.com/btp7jj

All I need is these two options. And because it's EcoPayz only functionality and not implemented in Omnipay core, it can be sorted on your repository level.

**Comment by dercoder** [comment]
I need only TransferUrl for transaction processing. Your example does not makes sense to me. It would be ok when we use omnipay notifyUrl for Transfer and Callback. This would make sense to me. 

If you insist, please ask omnipay community or the omnipay leader: https://github.com/greydnls

**Comment by Alex-Sh** [comment]
> I need only TransferUrl for transaction processing.
According to EcoPayz support response the only safe way to process transactions is CallbackUrl. But ok, I'll ask Omnipay

**Comment by dercoder** [comment]
Thx, Please keep me up 2 date. Ecopayz is paradox. Callback is only the safe way but its not enabled by default.

**Pull request closed without merging**
