### PR TITLE
adding missing functions for retrun url in gateway.

### PR DESCRIPTION
**Pull request by ahmedkhan847**
Add functions which were missing to set success, failure and transfer URL.

### CODE REVIEW

**Comment by dercoder** [comment]
Thats the wrong place to add them. This functions already exists in:
https://github.com/thephpleague/omnipay-common/blob/master/src/Common/Message/AbstractRequest.php#L551

**Comment by ahmedkhan847** [comment]
I was unable to get or set them. I got undefined function error

**Comment by dercoder** [comment]
Pls take a look here: https://github.com/thephpleague/omnipay
All gateway methods except `acceptNotification` take an `$options` array as an argument. The `acceptNotification` method
does not take any parameters and will access the HTTP URL variables or POST data implicitly. Each gateway differs in
which parameters are required, and the gateway will throw `InvalidRequestException` if you omit any required parameters.
All gateways will accept a subset of these options:

* card
* token
* amount
* currency
* description
* transactionId
* clientIp
* returnUrl
* cancelUrl

Pass the options through to the method like so:

```php
$card = new CreditCard($formData);
$request = $gateway->authorize(array(
    'amount' => '10.00', // this represents $10.00
    'card' => $card,
    'returnUrl' => 'https://www.example.com/return',
));
```

**Comment by ahmedkhan847** [comment]
hey thanks for letting me know I will close this request can you tell me how can I set callbackURL in it?

**Comment by dercoder** [comment]
callbackUrl = notifyUrl

**Comment by ahmedkhan847** [comment]
nope not that one. Their is an optional CallBackURL in ecopayz document which tells the transfer is complete or not.

**Comment by ahmedkhan847** [comment]
notifyURL is a transferUrl

**Comment by dercoder** [comment]
Why do you need the CallbackUrl? Its not enabled by default and TransferUrl will do the same

TransferUrl URL 
Merchant’s Listener URL (used for server to server calls between the Merchant and ecoPayz)

CallbackUrl (Not required) URL 
Merchants can receive XML notifications to monitor the final status of purchase transactions automatically via the ‘Callback’ URL.  
 
N.B! This function is not enabled by default. In order to enable ‘Callback’ you have to provide us (technicalsupport@ecopayz.com) with an URL and request activation of this feature for your Merchant account. It can be the same URL as your Listener or a different URL.

**Comment by ahmedkhan847** [comment]
Thanks man this will do the trick.

**Pull request closed without merging**
